version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-ecommerce-multivendor
    environment:
      MYSQL_DATABASE: ecommerce-multivendor
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql


volumes:
  mysql-data: