version: '3.8'
networks:
  ecmv1:
    external: true
services:
  mysql:
    image: mysql:latest
    container_name: mysql-ecommerce-multivendor
    environment:
      MYSQL_DATABASE: ecommerce-multivendor
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecmv1
  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka-ecommerce-multivendor
    hostname: localhost
    ports:
      - '9092:9092'  # Added listener port
      - '9093:9093'  # Added controller port
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - ecmv1

volumes:
  mysql-data: