spring:
  application:
    name: ecommerce-multivendor
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce-multivendor
    password: root
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: abc0905440632@gmail.com
    password: "wqrn fgrf wmvn vipx"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


server:
  servlet:
    context-path: /
  port: 8080

security:
  jwt:
    secretKey: ${SECURITY_JWT_SECRET_KEY}
    header: "Authorization"

vnpay:
  tmn-code: PBR8SGZ0
  hash-secret: 38M103D05N307NJIPAH8JO5IBC8QNRKB
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/vnpay/return
  ipn-url: http://localhost:8080/vnpay/ipn

